# Generated by Django 5.0.6 on 2025-01-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField(default=0)),
                ('address', models.TextField(default='address')),
                ('city', models.CharField(default='city', max_length=100)),
                ('state', models.CharField(default='state', max_length=100)),
                ('zip', models.CharField(default='0000', max_length=10)),
                ('country', models.CharField(default='country', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
