# Generated by Django 5.0.6 on 2025-01-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('pet', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_pet', 'Small Pet'), ('other', 'Other')], max_length=100)),
                ('treatment', models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'Checkup'), ('surgery', 'Surgery'), ('dental', 'Dental'), ('emergency', 'Emergency'), ('Grooming', 'Grooming'), ('other', 'Other')], max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
