# Generated by Django 5.0.6 on 2025-01-09 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_order_payment_status_bookappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('vaccine_type', models.CharField(max_length=20)),
                ('dosage', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('pet', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_pet', 'Small Pet'), ('other', 'Other')], max_length=100)),
                ('age', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_hospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
