# Generated by Django 5.0.6 on 2025-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_vaccinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinations',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
